#ifndef SERIAL_STATUS_H__
#define SERIAL_STATUS_H__


#define SERIAL_STATUS_SUCCESS                   0x00
#define SERIAL_STATUS_ERROR_UNKNOWN             0x80
#define SERIAL_STATUS_ERROR_INTERNAL            0x81
#define SERIAL_STATUS_ERROR_CMD_UNKNOWN         0x82
#define SERIAL_STATUS_ERROR_INVALID_STATE       0x83
#define SERIAL_STATUS_ERROR_INVALID_LENGTH      0x84
#define SERIAL_STATUS_ERROR_INVALID_PARAMETER   0x85
#define SERIAL_STATUS_ERROR_BUSY                0x86
#define SERIAL_STATUS_ERROR_INVALID_DATA        0x87
#define SERIAL_STATUS_ERROR_REJECTED            0x8e
#define SERIAL_STATUS_ERROR_TIMEOUT             0x93
#define SERIAL_STATUS_ERROR_INVALID_KEY_DATA    0x98

/** @} end of SERIAL_STATUS_CODES */

#endif
